spring:
  datasource:
    url: jdbc:clickhouse://127.0.0.1:8123/tutorial
    driver-class-name: ru.yandex.clickhouse.ClickHouseDriver
# mybatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true